# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dusti/projects/cmake_tutorials

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dusti/projects/cmake_tutorials

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dusti/projects/cmake_tutorials/CMakeFiles /home/dusti/projects/cmake_tutorials//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dusti/projects/cmake_tutorials/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named library1

# Build rule for target.
library1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 library1
.PHONY : library1

# fast build rule for target.
library1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library1.dir/build.make CMakeFiles/library1.dir/build
.PHONY : library1/fast

#=============================================================================
# Target rules for targets named cmake_tutorials

# Build rule for target.
cmake_tutorials: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cmake_tutorials
.PHONY : cmake_tutorials

# fast build rule for target.
cmake_tutorials/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_tutorials.dir/build.make CMakeFiles/cmake_tutorials.dir/build
.PHONY : cmake_tutorials/fast

#=============================================================================
# Target rules for targets named printer

# Build rule for target.
printer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 printer
.PHONY : printer

# fast build rule for target.
printer/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/printer.dir/build.make test/CMakeFiles/printer.dir/build
.PHONY : printer/fast

src/file1.o: src/file1.cpp.o
.PHONY : src/file1.o

# target to build an object file
src/file1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library1.dir/build.make CMakeFiles/library1.dir/src/file1.cpp.o
.PHONY : src/file1.cpp.o

src/file1.i: src/file1.cpp.i
.PHONY : src/file1.i

# target to preprocess a source file
src/file1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library1.dir/build.make CMakeFiles/library1.dir/src/file1.cpp.i
.PHONY : src/file1.cpp.i

src/file1.s: src/file1.cpp.s
.PHONY : src/file1.s

# target to generate assembly for a file
src/file1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/library1.dir/build.make CMakeFiles/library1.dir/src/file1.cpp.s
.PHONY : src/file1.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_tutorials.dir/build.make CMakeFiles/cmake_tutorials.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_tutorials.dir/build.make CMakeFiles/cmake_tutorials.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_tutorials.dir/build.make CMakeFiles/cmake_tutorials.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/printer.o: src/printer.cpp.o
.PHONY : src/printer.o

# target to build an object file
src/printer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_tutorials.dir/build.make CMakeFiles/cmake_tutorials.dir/src/printer.cpp.o
.PHONY : src/printer.cpp.o

src/printer.i: src/printer.cpp.i
.PHONY : src/printer.i

# target to preprocess a source file
src/printer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_tutorials.dir/build.make CMakeFiles/cmake_tutorials.dir/src/printer.cpp.i
.PHONY : src/printer.cpp.i

src/printer.s: src/printer.cpp.s
.PHONY : src/printer.s

# target to generate assembly for a file
src/printer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmake_tutorials.dir/build.make CMakeFiles/cmake_tutorials.dir/src/printer.cpp.s
.PHONY : src/printer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cmake_tutorials"
	@echo "... library1"
	@echo "... printer"
	@echo "... src/file1.o"
	@echo "... src/file1.i"
	@echo "... src/file1.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/printer.o"
	@echo "... src/printer.i"
	@echo "... src/printer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

